### ISSUE TITLE
Divisors & Data Fields in Current Systems

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#13]
A lot of information will need to be captured in the Reporting app, including data that was historically in provided through CIIP and SWRS. Doing a scan of divisors and datafields in our current systems will help us understand and identify what will be required for the future system. 

**Acceptance Criteria:**
- [x] Find out from the B.A. how best to go about verifying future datafield requirements; Do we need CIIP and SWRS reference documents to compare to or not? YES
- [x] Ask the B.A. about the data currently being requested for CIIP: Is any of this data going to be required for our future system? Is anything changing?  YES, data from CIIP will be required and some will be changed/added
- [x] Review Andrea's SWRS data spreadsheet with SMEs to understand, generally, what information from SWRS is still relevant 

**Goal of ticket:**
- Understand from the B.A. what value our current data collection through SWRS & CIIP has for design of the future Reporting module.

**Comment by jaimiebutton** [comment]
Is this a good place to bring back the 'what data staff need' work done by @andrea-williams and Reporting & Analytics?

**Comment by Dianadec** [comment]
Refinement notes: Might need an epic - this type of work will be ongoing in terms of discussions with the business area and as policy gets updated.

**Comment by patriciarussellCAS** [comment]
I have updated this ticket to capture the first stages of datafield requirement information gathering. I will add additional tickets to capture all the other items we used to have in this ticket. Will likely need DEV review!

**Comment by patriciarussellCAS** [comment]
@mikevespi Tagging you in the ticket for your review. The data we've collected so far can be found on Team in the "Carbon Pricing Transition SMEs" channel, under "Files" > "Reporting App"

**Comment by patriciarussellCAS** [comment]
Adding link to Compliance Miro board: https://miro.com/app/board/uXjVPZNMFas=/?moveToWidget=3458764566075212967&cot=14

**Comment by Dianadec** [comment]
"Review C&E Miro board" AC might need to also be a ticket to go over it with the C&E team

**Comment by Dianadec** [comment]
Include QB's guidance documents

**Comment by patriciarussellCAS** [comment]
Hey Team - here is a summary of information gathered from my initial talk with Robb T. This is also in our SME OneNote doc. 

[Jan 10 2024] Summary of Meeting between Patricia and Robb T 

 Q: Is there any value in going through the data fields currently in SWRS?  
A: Yes. The data we are requesting in the new system will be the same as what's in SWRS 
It would be helpful to review SWRS data alongside the related WCI methodology, as this determined much of the data flow in the system 
WCI: https://www2.gov.bc.ca/assets/gov/environment/climate-change/ind/quantification/wci-2011.pdf

Also recommends we review Qinghan's guidance document for SWRS 
https://www2.gov.bc.ca/assets/gov/environment/climate-change/ind/reporting-emissions/2019/illustrated_guidebook_of_bcs_ghg_reporting_system.pdf

Q: What data in CIIP is additional to the data requested through SWRS? 
A: Fuel amounts are not requested in SWRS but will continue to be required (for example fuel amounts for venting/flaring) 
- For Cement, CIIP asks for "wet" vs "dry" coal, for example.  
- Often the differences are because of what is required for reporting vs what is required for carbon tax purposes. So while that may not apply when we change how we tax carbon, we may want to continue to ask for this information so that our data can be audited; for example so it can be compared to the fuel purchases with the carbon tax exemption. (PR note: more to dig into here on what is required vs good policy vs nice to have) 
- Product data is not requested in SWRS but will continue to be required in the new system. It will be less important  

 Q: Can we categorize data for each reporter by NAICS code, or sector?  
A: Likely a combination of things, including emissions categories (for example "general stationary combustion"), sectors and NAICS codes 

 
Robb also flagged that the BC Corporate Registry (which will be requested at Registration) was historically input incorrectly so we should watch for errors in that field.

**Comment by patriciarussellCAS** [comment]
I've updated this ticket to hopefully be more clear on the goal. I've moved the SWRS/CIIP demos out and will create a separate ticket for those. Thanks!

**Comment by patriciarussellCAS** [comment]
Updated the scope of this ticket and moved next steps into a new ticket #152 
Closing this ticket now!
