### ISSUE TITLE
Explore monorepo tooling options

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-reporting#158]
#### Describe the task

Moving to a single repository does not have to mean a slow unmanageable monolith. There are tools that make monorepos an extremely efficient way to manage and coordinate multiple projects. While there are plenty of options, the two that standout (to me at least) are Nx and Turborepo. Turbo because it is made by Vercel, the creators of NextJS. Nx because it drastically outperforms the alternatives in many ways (particularly fast build and CI processes), and has native support for NextJS as well. 

Consider while exploring these tools the effort of handling these processes by ourselves, in comparison to the learning curve experienced while demoing monorepos.

#### Acceptance Criteria

- [x] Comparison of monorepo tools, features, performance, and ease of use
- [x] Test the main contender(s) in our setup
- [x] Document the findings, tradeoffs, and benefits.

#### Additional context

The creators of the top monorepo tools came together and wrote up documentation on the approach itself, as well has offer feature comparisons across their products. This can be found here https://monorepo.tools/ and is a great introduction to the concepts and features that can be offered.

**Comment by mikevespi** [comment]
I have begun looking at Nx, but am off tomorrow so will leave this in the Sprint Backlog for now. Other devs feel free to jump in on this as well, let's just make sure we're synchronizing our work if you do!

**Comment by mikevespi** [comment]
Broke card #173 out of this card, will discuss closing this with team.
cc @joshgamache

**Comment by mikevespi** [comment]
After discussions today we have opted to try Nx. Research done independantly by the Giraffe devs all lead back to Nx being the best fit for our needs. It has the highest performance in build optimization, allows for shared packages, and side-by-side apps. One of the main deciding factors was also the volume and quality of their documentation, which should allow the team to more effectively and efficiently adapt the new tool. 

#173 will be reworded to reflect the next steps.

**Comment by joshgamache** [comment]
Adding my notes from Turborepo exploration here, so there in a shared location in case we ever need them. Not spending time to distill them, since we won't be going this way for now.

## Jot notes

- Backed up by Vercel, fits with our Next.js stack.
- It's *fast*. 
- Builds on workspace features of Yarn, NPM, PNPM and extends them.
- Had issues getting the examples working with Yarn, but I suspect that's an issue with *my* yarn.
- Works with Django, just need to drop in a `package.json` with a name and scripts. 
- We could configure a self-hosted remote task cache [other than Vercel](https://turbo.build/repo/docs/core-concepts/remote-caching#remote-caching-api) to take advantage of the speed increases. 
	- There are open-source Helm charts to deploy this. EX. [GitHub - ducktors/turborepo-remote-cache: Open source implementation of the Turborepo custom remote cache server.](https://github.com/ducktors/turborepo-remote-cache). And we could use our existing Terrafrom charts to [deploy supporting storage buckets in GCP](https://ducktors.github.io/turborepo-remote-cache/supported-storage-providers#google-cloud-storage) , and could be integrated with GitHub actions if we choose to.

## Random links

- [changesets/changesets: 🦋 A way to manage your versioning and changelogs with a focus on monorepos (github.com)](https://github.com/changesets/changesets)
- [Share Auth Session between NextJs Multi-zones apps using NextAuth.js | by Badjessa Roméo Bahoumda | Medium](https://medium.com/@badjessab/share-auth-session-between-nextjs-multi-zones-apps-using-nextauth-js-5bab51bb7e31)
- Next.js zones? Does this work with what we're trying to do? [Deploying: Multi Zones | Next.js (nextjs.org)](https://nextjs.org/docs/pages/building-your-application/deploying/multi-zones) and an example [next.js/examples/with-zones at canary · vercel/next.js (github.com)](https://github.com/vercel/next.js/tree/canary/examples/with-zones)


## Nx remote caching

While I was messing around with Turborepo, I read about how you can set up remote caching seperate from Vercel. Not sure if it had been discussed yet, but it looks like there's similar support in Nx without needing to use Nx Cloud ([one example here](https://github.com/MansaGroup/nx-gcs-remote-cache), but I'm sure there might be others). With the Terraform+GCS chart we have, makes for a seemingly straightforward bonus.

**Comment by pbastia** [comment]
@mikevespi and @joshgamache I'm thinking we might be able to call this done?
