### ISSUE TITLE
How will LFO/facility admin data flow in our system between Reg. & Rep.?

### ISSUE THREAD

**Issue by jaimiebutton** [bcgov/cas-reporting#28]
LFO's need to submit facility-level data for Reporting, but what information will be required for Registration at the facility level? 
What specific administrative data from facilities is required (if at all?) for registration? How does this flow into reporting?

**Acceptance Criteria:**
- [x] Sync up with Hanna on work to date from Registration
- [x] Pull in registration fields marked priority 2 & 3 (can be found in SME channel reg. fields spreadsheet)
- [ ] Create a list of unknowns, framed as clear questions for the business area (and who should answer each one)
- [ ] Map out + add to our blueprint where in our system LFO/IF admin data should live; what does this process look like for the users?

**Goal of this ticket:**
Confirm high-level process for how facility-level admin data is entered into our system

**Comment by patriciarussellCAS** [comment]
@hannavovk tagging you so you're aware of this ticket. As of oct 18th the understanding is that LFO facility data will NOT be part of the Registration MVP. The business area is still figuring out whether this data will end up in registration or reporting, so still to be confirmed.

**Comment by suhafa** [comment]
Some outcomes from the wireframe party session on Tuesday, 12th December:
1) To decide: We talked about how to position Registration + Reporting in the app. Will it be separate apps for each (separate domain links?) Will it look appear as one app or separate to the external user? 
 
2) To decide: How will we add Tier 2 & 3 fields in Registration for post-MVP? From a technical perspective, what would make more sense: adding those additional fields to our forms when the user needs to complete them for their remaining OBPS registration? When do we add those, right before reporting requirements start so they can submit both together or much in advance? This requires some regulation info from business area for weighing in too. We also want to know if the business area wants to validate the Tier 2 & 3 fields as well, so that would mean validating twice in the app. 
 
3) To design: I'd be happy to take a stab at some really lo-fi mockups for the above and present them as options to the business area once we have some internal understanding as to how we want to proceed.

**Comment by jaimiebutton** [comment]
Work done:
- Held 2 wireframe parties
- Made a rough map of how this data will be handled
- Made some rough wireframes
