### ISSUE TITLE
Design Backlog: Operation Information Page

### ISSUE THREAD

**Issue by patriciarussellCAS** [bcgov/cas-reporting#298]
This is a design review follow-up ticket to #196 

Here are the design review notes from Suha:
- [x] update the alert banner. Addressed in #432 
- [x] BORO ID and BCGHG ID are greyed out and meant to be auto-populated with information we will have on the user. It can't be edited. Can we visually reflect this? In Figma, we have #F2F2F2 (bc-background-grey) fill such fields
- [x] The button placement , stylization and sizing at the end (for Save, Continue, Cancel) are different than in Figma
- [x] I wasn't able to test out whether Reporting Activities, Regulated Products, Operation representative were multi-select drop-downs where we can select more than one entry
- [x] The header of the form looks different than what we have in Figma. I do believe we have this styled component we can borrow from Moose

**Comment by patriciarussellCAS** [comment]
Needs updating. Many of these have been addressed already.

**Comment by zoeyli-46** [comment]
zoey to check which ones have been implemented already and then update this ticket

**Comment by zoeyli-46** [comment]
@patriciarussellCAS I believe we can close this ticket. Checkbox 2 and 4 are already implemented. Checkbox 1 is being implemented in a different ticket #432 

RE: third checkbox: "The button placement , stylization and sizing at the end (for Save, Continue, Cancel) are different than in Figma" <- the only difference is that instead of "continue", in dev it says "save & continue" which is actually better than just continue, so I mark this checkbox as done.

RE: last checkbox: "The header of the form looks different than what we have in Figma. I do believe we have this styled component we can borrow from Moose", it looks the same currently.

**Comment by patriciarussellCAS** [comment]
Thanks Zoey. Works for me. I will close this.
