### ISSUE TITLE
"Cancel" or "Back" button behaviour on reporting forms

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-reporting#381]
#### Description:
Refer to this [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=24707-7234&t=x7HowsJ2xqvG3yYI-4) for guidance on where to use a Cancel button versus a Back button. 

In summary, 
Cancel button should appear on Add, so that users can "cancel" accidentally creating something.
Cancel button should appear on pages where the user was "viewing" something and they clicked "edit", so they can cancel accidentally editing something they already submitted/saved.

Back should appear when viewing something, (i.e., they clicked View Details), or when submitting something i.e., on Register an Operation or when filling out a Report. 

In Reporting, the Back button behaviour should navigate through the task list, behaving the same as the “continue” button. I.e., if the user is on the Attachments page in Signoff & Submit, then back takes them to Verification page. Clicking back from Verification would take them to the Compliance Summary page, and so on.

Note: The task list behaves differently in Reporting and Registration. In Registration, the task list is sections of the same page, instead of navigating to different pages.

Explanation on why back button is important on the Report forms: While users _can_ use a task list to navigate backwards, when conducting user testing for Registering an Operation (similar to Reporting), we had the buttons “save and continue” and “cancel”. However, user testers still requested a "back" button otherwise they believe they are unable to change what they have written on the previous page.

#### Acceptance Criteria:

Given
When
Then

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by pbastia** [comment]
cc @patriciarussellCAS @zoeyli-46

**Comment by zoeyli-46** [comment]
Hey @pbastia @dleard I created this [Page](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=24707-7234&t=x7HowsJ2xqvG3yYI-4) about when to use a Cancel or Back button. 

In summary, 
Cancel button should appear on Add, so that users can "cancel" accidentally creating something. Also, on pages where the user was "viewing" something and they clicked "edit", so they can cancel accidentally editing something they already submitted/saved.

Back should appear when viewing something, (i.e., they clicked View Details), or when submitting something i.e., on Register an Operation or when filling out a Report. On Reporting, the Back button behaviour should navigate through the task list, behaving the same as the “continue” button. I.e., if the user is on the Attachments page in Signoff & Submit, then back takes them to Verification page. Clicking back from Verification would take them to the Compliance Summary page.

Explanation on why back button is important on the Report forms: While users _can_ use a task list to navigate backwards, when conducting user testing for Registering an Operation (similar to Reporting), we had the buttons “save and continue” and “cancel”. However, user testers were looking for a back button so they can go to the previous page, otherwise they think that the system doesn’t let them go back to change something they entered in the form.

Are there other possible paths that we need to think about for the buttons?

**Comment by rdromey** [comment]
@dleard to write tech debt ticket to cover the dev work and then we can close this ticket

**Comment by rdromey** [comment]
Covered by #392 so we are closing this now.
